version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(mobile)"
    groups:
      mobile-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:15"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "deps(actions)"
    groups:
      github-actions:
        patterns:
          - "*"

